name: DZTablist
version: 1.0.0
main: online.demonzdevelopment.DZTablist
api-version: '1.16'
authors: [DemonZ Development]
description: Advanced Tablist plugin with extensive customization

depend:
  - LuckPerms
  - PlaceholderAPI

commands:
  dztablist:
    description: Main plugin command
    usage: /<command> [reload|cpu|help]
    permission: dztablist.admin
  bossbar:
    description: Toggle bossbar
    usage: /<command> toggle
    permission: dztablist.bossbar.toggle
  scoreboard:
    description: Toggle scoreboard
    usage: /<command> toggle
    permission: dztablist.scoreboard.toggle

permissions:
  dztablist.admin:
    description: Access to admin commands
    default: op
  dztablist.bossbar.toggle:
    description: Toggle bossbar visibility
    default: true
  dztablist.scoreboard.toggle:
    description: Toggle scoreboard visibility
    default: true
  dztablist.seeall:
    description: See all players in per-world playerlist mode
    default: op
